#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Preprocess feature-fusion test cases only, using an existing nnU-Net plans file.

This is intended for the case where train/val are already preprocessed and only
test cases need to be added to:
    preprocessed_data/Task003_llm_fusion/nnUNetData_plans_v2.1_stage0

It does not re-run experiment planning and does not delete existing train/val
preprocessed files.
"""

import argparse
from collections import OrderedDict
import json
import multiprocessing as mp
import pickle
import shutil
import sys
from pathlib import Path

AUTO_RG_ROOT = Path(__file__).resolve().parents[1]
if str(AUTO_RG_ROOT) not in sys.path:
    sys.path.insert(0, str(AUTO_RG_ROOT))

from batchgenerators.utilities.file_and_folder_operations import maybe_mkdir_p

from preprocess.cropping_llm_feature_fusion import ImageCropper, get_case_identifier
from preprocess.preprocessing_llm_feature_fusion import GenericPreprocessor as FeatureFusionPreprocessor


def load_json(path):
    with Path(path).open("r", encoding="utf-8") as f:
        return json.load(f)


def load_pickle(path):
    with Path(path).open("rb") as f:
        return pickle.load(f)


def resolve_path(path):
    path = Path(path)
    return path if path.is_absolute() else path.resolve()


def build_case_lists(dataset_json):
    data = load_json(dataset_json)
    case_lists = []
    for entry in data["training"]:
        cur_case = list(entry.get("images", [entry["image"]]))
        cur_case.append(entry["label1"])
        cur_case.append(entry["label2"])
        case_lists.append(cur_case)
    return case_lists


def repeat_mapping_to_modalities(mapping, num_modalities):
    if len(mapping) == num_modalities:
        return mapping
    if len(mapping) != 1:
        raise RuntimeError(
            f"Cannot expand mapping with {len(mapping)} entries to {num_modalities} modalities."
        )
    value = next(iter(mapping.values()))
    return OrderedDict((i, value) for i in range(num_modalities))


def repeat_intensityproperties_to_modalities(intensityproperties, num_modalities):
    if intensityproperties is None or len(intensityproperties) == num_modalities:
        return intensityproperties
    if len(intensityproperties) != 1:
        raise RuntimeError(
            f"Cannot expand intensityproperties with {len(intensityproperties)} entries to {num_modalities} modalities."
        )
    value = next(iter(intensityproperties.values()))
    return OrderedDict((i, value) for i in range(num_modalities))


def preprocess_one(args):
    preprocessor, target_spacing, case_identifier, output_folder_stage, cropped_dir, all_classes = args
    preprocessor._run_internal(
        target_spacing,
        case_identifier,
        str(output_folder_stage),
        str(cropped_dir),
        None,
        all_classes,
    )


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--dataset_json",
        type=Path,
        default=Path("../../raw_data/nnUNet_raw_data/Task003_llm_fusion/dataset_test_only.json"),
        help="Test-only nnU-Net dataset JSON generated by build_feature_fusion_nnunet_dataset_test_only.py.",
    )
    parser.add_argument(
        "--plans_file",
        type=Path,
        default=Path("utils_file/nnUNetPlansv2.1_plans_3D.pkl"),
        help="Existing plans file used by feature-fusion training.",
    )
    parser.add_argument(
        "--preprocessed_task_dir",
        type=Path,
        default=Path("../preprocessed_data/Task003_llm_fusion"),
        help="Existing Task003_llm_fusion preprocessed directory.",
    )
    parser.add_argument(
        "--cropped_tmp_dir",
        type=Path,
        default=Path("../raw_data/nnUNet_cropped_data/Task003_llm_fusion_test_only_tmp"),
        help="Temporary cropped folder for test cases.",
    )
    parser.add_argument(
        "-tf",
        "--threads",
        type=int,
        default=1,
        help="Number of worker processes for cropping and preprocessing.",
    )
    parser.add_argument(
        "--overwrite_cropped",
        action="store_true",
        help="Overwrite existing temporary cropped test files.",
    )
    parser.add_argument(
        "--overwrite_preprocessed",
        action="store_true",
        help="Recompute test cases even if their preprocessed .npz/.pkl already exist.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    dataset_json = resolve_path(args.dataset_json)
    plans_file = resolve_path(args.plans_file)
    preprocessed_task_dir = resolve_path(args.preprocessed_task_dir)
    cropped_tmp_dir = resolve_path(args.cropped_tmp_dir)

    plans = load_pickle(plans_file)
    data_identifier = plans["data_identifier"]
    stage = sorted(plans["plans_per_stage"].keys())[-1]
    output_folder_stage = preprocessed_task_dir / f"{data_identifier}_stage{stage}"
    maybe_mkdir_p(str(output_folder_stage))

    case_lists = build_case_lists(dataset_json)
    case_identifiers = [get_case_identifier(case) for case in case_lists]

    cases_to_process = []
    for case, case_identifier in zip(case_lists, case_identifiers):
        out_npz = output_folder_stage / f"{case_identifier}.npz"
        out_pkl = output_folder_stage / f"{case_identifier}.pkl"
        if args.overwrite_preprocessed or not (out_npz.is_file() and out_pkl.is_file()):
            cases_to_process.append((case, case_identifier))

    print("dataset_json:", dataset_json)
    print("plans_file:", plans_file)
    print("preprocessed_stage_dir:", output_folder_stage)
    print("cropped_tmp_dir:", cropped_tmp_dir)
    print("total cases in dataset_json:", len(case_lists))
    print("cases needing preprocessing:", len(cases_to_process))

    if not cases_to_process:
        print("Nothing to do.")
        return

    if args.overwrite_cropped and cropped_tmp_dir.is_dir():
        shutil.rmtree(cropped_tmp_dir)
    maybe_mkdir_p(str(cropped_tmp_dir))

    cropper = ImageCropper(args.threads, str(cropped_tmp_dir))
    cropper.run_cropping(
        [case for case, _ in cases_to_process],
        overwrite_existing=args.overwrite_cropped,
    )

    gt_src = cropped_tmp_dir / "gt_segmentations"
    gt_dst = preprocessed_task_dir / "gt_segmentations"
    maybe_mkdir_p(str(gt_dst))
    if gt_src.is_dir():
        for seg_path in gt_src.glob("*.nii.gz"):
            shutil.copy2(seg_path, gt_dst / seg_path.name)

    num_modalities = len(case_lists[0]) - 2
    normalization_schemes = repeat_mapping_to_modalities(
        plans["normalization_schemes"],
        num_modalities,
    )
    use_nonzero_mask = repeat_mapping_to_modalities(
        plans["use_mask_for_norm"],
        num_modalities,
    )
    intensityproperties = repeat_intensityproperties_to_modalities(
        plans["dataset_properties"]["intensityproperties"],
        num_modalities,
    )
    transpose_forward = plans["transpose_forward"]
    all_classes = plans.get("all_classes", plans["dataset_properties"]["all_classes"])
    target_spacing = plans["plans_per_stage"][stage]["current_spacing"]

    preprocessor = FeatureFusionPreprocessor(
        normalization_schemes,
        use_nonzero_mask,
        transpose_forward,
        intensityproperties,
    )

    preprocess_args = [
        (preprocessor, target_spacing, case_identifier, output_folder_stage, cropped_tmp_dir, all_classes)
        for _, case_identifier in cases_to_process
    ]

    if args.threads > 1:
        with mp.Pool(args.threads) as pool:
            pool.map(preprocess_one, preprocess_args)
    else:
        for item in preprocess_args:
            preprocess_one(item)

    print("Done.")
    print("Generated/updated test preprocessed cases:", len(cases_to_process))


if __name__ == "__main__":
    main()
